# Generated by Django 3.0 on 2020-03-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kendala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlg_kendala', models.DateField()),
                ('bidang', models.IntegerField(choices=[(1, 'Kepesertaan'), (2, 'Pelayanan'), (3, 'Keuangan'), (4, 'Umum & SDM'), (5, 'Wasrik'), (6, 'IT')])),
                ('keterangan', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
