# Generated by Django 3.0 on 2020-03-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kendala',
            old_name='tlg_kendala',
            new_name='tgl_kendala',
        ),
    ]
