# Generated by Django 3.0.5 on 2020-04-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi_apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karyawan',
        ),
    ]
