# Generated by Django 3.0.5 on 2020-04-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absensi_apps', '0003_auto_20200402_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan_absen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
